### ISSUE TITLE
template-generator won't build on ubuntu due to fsevents in package-lock.json

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/monorepo#27]
`fsevents` doesn't exist on linux but it's required by the template-generator package-lock.json. This also causes `lerna bootstrap` to fail for the whole project. Delete the `package-lock.json` and it builds fine (and makes a new `package-lock.json`)

 It's probably possible to mark it optional or something, alternatively maybe we could just `.gitignore` the `package-lock.json`.

```
ed@rc-dev-5:~/mt/packages/template-generator$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN deprecated fsevents@2.1.2: "Please update to latest v2.3 or v2.2"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ed/.npm/_logs/2021-08-20T00_53_51_953Z-debug.log
```

**Comment by carlosfebres** [comment]
@edmundedgar I made the `fsevents` library an optional dependency in this commit https://github.com/RealityETH/monorepo/pull/30/commits/9b08b16c8d93cc57202bc2ca3dce0770bf6db48f.
I'm a bit surprised this is happening in Ubuntu since I'm using it and I'm not getting this error.
I couldn't reproduced this error so please let me know if this change fixes the issue, if not we could ignore the `package-lock.json` as you suggest.

**Comment by edmundedgar** [comment]
Didn't fix it, maybe my npm is too old

**Comment by edmundedgar** [comment]
Deleted and recreated so we could push the other packages with lerna, builds for me now, not sure if it still builds for @carlosfebres
