### ISSUE TITLE
template-generator expects to be at the root of the site

### ISSUE THREAD

**Issue by edmundedgar** [RealityETH/monorepo#28]
When I build the package I get a file at `build/index.html` that shows a blank screen. It seems to be trying to load CSS and JS from places like `/static/js/2.b90f966f.chunk.js`. Change those relative URLs like `./static/js/2.b90f966f.chunk.js` and it displays fine. 

We'll probably ultimately want to deploy this at something like `reality.eth/dapp/template-generator`, so it would be useful if it built with relative URLs.

**Comment by carlosfebres** [comment]
This issue has been solved in this commit https://github.com/RealityETH/monorepo/pull/30/commits/4b86b942b83a1c8cb23689861fc6290614bbea88
The homepage field is set to `./` in the `package.json`. now CSS and JS files are loaded from that path.
